# =============================================================
# pg_hba.conf — Todos los nodos del clúster
# Permite conexiones locales, replicación y repmgr
# =============================================================

# Acceso local (socket Unix)
local   all             postgres                                trust
local   all             all                                     scram-sha-256
local   replication     all                                     trust

# Acceso dentro de la red del clúster
host    all             postgres        172.29.0.0/24           trust
host    all             all             172.29.0.0/24           scram-sha-256

# Replicación streaming desde cualquier nodo del clúster
host    replication     replicator      172.29.0.0/24           scram-sha-256
host    replication     repmgr          172.29.0.0/24           scram-sha-256

# Base de datos repmgr accesible desde todos los nodos
host    repmgr          repmgr          172.29.0.0/24           scram-sha-256

# Acceso externo (herramientas del host: psql, DBeaver, etc.)
host    all             all             0.0.0.0/0               scram-sha-256
host    replication     replicator      0.0.0.0/0               scram-sha-256
