# =============================================================
# postgresql.conf — Nodo PRIMARIO
# pg-primary (172.20.0.10)
# =============================================================

# ── Conexión ──────────────────────────────────────────────────
listen_addresses            = '*'
port                        = 5432
max_connections             = 200

# ── WAL y replicación ─────────────────────────────────────────
wal_level                   = replica
max_wal_senders             = 10
max_replication_slots       = 10
wal_keep_size               = 512MB
hot_standby                 = on

# ── Timeouts de replicación ───────────────────────────────────
wal_sender_timeout          = 60s
wal_receiver_timeout        = 60s

# ── Archivado WAL ─────────────────────────────────────────────
archive_mode                = on
archive_command             = 'test ! -f /mnt/wal_archive/%f && cp %p /mnt/wal_archive/%f'
archive_timeout             = 60s

# ── Replicación SÍNCRONA ──────────────────────────────────────
# FIRST 1: esperar confirmación de pg-standby1 (prioridad)
# Si pg-standby1 cae, pg-standby2 pasa a síncrono automáticamente
synchronous_commit          = on
synchronous_standby_names   = 'FIRST 1 (pgstandby1,pgstandby2)'

# ── Checkpoint ────────────────────────────────────────────────
checkpoint_completion_target = 0.9
max_wal_size                = 1GB
min_wal_size                = 256MB

# ── Performance ───────────────────────────────────────────────
shared_buffers              = 256MB
effective_cache_size        = 768MB
work_mem                    = 16MB
maintenance_work_mem        = 128MB

# ── Logging ───────────────────────────────────────────────────
log_destination             = 'stderr'
logging_collector           = off
log_min_messages            = warning
log_min_error_statement     = error
log_connections             = on
log_disconnections          = on
log_line_prefix             = '%t [%p] %u@%d '
log_replication_commands    = on

# ── Seguridad ─────────────────────────────────────────────────
password_encryption         = scram-sha-256

# ── repmgr ────────────────────────────────────────────────────
shared_preload_libraries = 'repmgr'  # FIX: obligatorio para que repmgrd pueda usar memoria compartida
