apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: postgres-lab
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: admin@lab.com
  PGADMIN_DEFAULT_PASSWORD: admin123

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers
  namespace: postgres-lab
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "PostgreSQL Lab (K8s)",
          "Group": "Servers",
          "Host": "postgres",
          "Port": 5432,
          "MaintenanceDB": "labdb",
          "Username": "pgadmin",
          "SSLMode": "prefer"
        }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: postgres-lab
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          ports:
            - containerPort: 80
              name: web
          envFrom:
            - secretRef:
                name: pgadmin-secret
          env:
            - name: PGADMIN_CONFIG_SERVER_MODE
              value: "False"
            - name: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
              value: "False"
          volumeMounts:
            - name: servers
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
      volumes:
        - name: servers
          configMap:
            name: pgadmin-servers

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: postgres-lab
  labels:
    app: pgadmin
spec:
  selector:
    app: pgadmin
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: 80
      nodePort: 30050
