# =============================================================
# pg_hba.conf — Laboratorio de Seguridad
# =============================================================

# ── Socket Unix local (sin contraseña para postgres) ─────────
local   all             postgres                                trust
local   all             all                                     scram-sha-256

# ── Red interna Docker (acceso completo para el lab) ─────────
host    all             postgres        172.0.0.0/8             trust
host    all             all             172.0.0.0/8             scram-sha-256

# ── Acceso externo desde el host ─────────────────────────────
# Sin SSL (para conexiones básicas del lab desde el host)
host    all             postgres        0.0.0.0/0               trust
host    all             all             0.0.0.0/0               scram-sha-256

# SSL obligatorio para usuarios de aplicación (sección 5 del lab)
# Descomentar cuando se active la práctica de SSL:
# hostssl  all   app_backend   0.0.0.0/0   scram-sha-256
# hostssl  all   dba_ana       0.0.0.0/0   cert clientcert=verify-full
