# =============================================================
# repmgr.conf — STANDBY 2 (node_id=3, priority=50)
# Segunda opción de failover (prioridad más baja)
# =============================================================

node_id                 = 3
node_name               = 'pg-standby2'
conninfo                = 'host=pg-standby2 port=5432 dbname=repmgr user=repmgr password=repmgr_lab connect_timeout=5'
data_directory          = '/var/lib/postgresql/data'

pg_bindir               = '/usr/lib/postgresql/16/bin'

log_file                = '/var/log/repmgr/repmgr.log'
log_level               = INFO
log_facility            = STDERR

# ── Failover automático ───────────────────────────────────────
failover                = automatic
priority                = 50

promote_command         = '/usr/lib/postgresql/16/bin/repmgr standby promote -f /etc/repmgr/repmgr.conf'
follow_command          = '/usr/lib/postgresql/16/bin/repmgr standby follow -f /etc/repmgr/repmgr.conf --upstream-node-id=%n'

monitor_interval_secs   = 5
reconnect_attempts      = 4
reconnect_interval      = 5

primary_visibility_consensus = false

pg_basebackup_options   = '--wal-method=stream --checkpoint=fast'
event_notification_command  = '/scripts/notify_event.sh %n %e %s "%t" "%d"'
monitoring_history      = yes
