# =============================================================
# repmgr.conf — Nodo PRIMARIO (node_id=1)
# =============================================================

node_id                 = 1
node_name               = 'pg-primary'
conninfo                = 'host=pg-primary port=5432 dbname=repmgr user=repmgr password=repmgr_lab connect_timeout=5'
data_directory          = '/var/lib/postgresql/data'

# Binarios PostgreSQL dentro del contenedor
pg_bindir               = '/usr/lib/postgresql/16/bin'

# Logs
log_file                = '/var/log/repmgr/repmgr.log'
log_level               = INFO
log_facility            = STDERR

# ── Failover automático ───────────────────────────────────────
failover                = automatic
priority                = 100

promote_command         = '/usr/lib/postgresql/16/bin/repmgr standby promote -f /etc/repmgr/repmgr.conf'

follow_command          = '/usr/lib/postgresql/16/bin/repmgr standby follow -f /etc/repmgr/repmgr.conf --upstream-node-id=%n'

# ── Monitorización de conectividad ────────────────────────────
monitor_interval_secs   = 5
reconnect_attempts      = 4
reconnect_interval      = 5

# ── SSH (no se usa en contenedores — se usa repmgrd directo) ──
ssh_options             = '-o StrictHostKeyChecking=no -o ConnectTimeout=5'

# ── pg_basebackup ─────────────────────────────────────────────
pg_basebackup_options   = '--wal-method=stream --checkpoint=fast'

# ── Notificaciones ────────────────────────────────────────────
event_notification_command  = '/scripts/notify_event.sh %n %e %s "%t" "%d"'

# ── Monitorización histórica ──────────────────────────────────
monitoring_history      = yes
