# =============================================================
# pg_hba.conf — Configuración SSL para el lab
# =============================================================

# Conexiones locales por socket Unix (administración interna)
local   all             all                                     trust

# localhost sin SSL — permite disable/allow/prefer para el lab
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256

# Red Docker — SOLO SSL (bloquea conexiones no cifradas desde red)
hostssl    all          all             0.0.0.0/0               scram-sha-256

# Bloquear explícitamente conexiones sin SSL desde red
hostnossl  all          all             0.0.0.0/0               reject
